# Note: Workflows must be in the default branch to appear in Actions tab
# To make it visible in other branches, we need to add path filters
name: Docker CI

on:
  push:
    branches:
      - 'feat/**'  # Run only on branches starting with 'feat/'
      - 'hamid*'    # Also catch branches like 'feat-123'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Verify checkout
        run: |
          echo "Current branch: $(git branch --show-current)"
          echo "Git status:"
          git status
          echo "Directory contents:"
          ls -la
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Sets up the Buildx builder

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/dockerfiles/polkadot/polkadot_builder.Dockerfile
          push: false  # Only build, don't push
          cache-from: type=gha  # Uses GitHub Actions cache
          cache-to: type=gha,mode=max  # Stores cache in GitHub Actions

